application: snptzapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: receive_mail.py

- url: /qreminders
  script: queue_reminders.py
  login: admin

- url: /qdigests
  script: queue_digests.py
  login: admin

- url: /sendmail
  script: main.py
  login: admin

- url: /signup
  script: signup.py
  login: required

- url: /
  script: main.py

- url: /settings
  script: main.py
  login: required

- url: /info
  script: main.py
  login: required

- url: /sidebar
  script: main.py
  login: required

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robot.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /fixtures
  script: load_data.py
  login: required

- url: /taskweek/show/(realistic|optimistic)/([^/]*)
  script: main.py
  login: required

- url: /taskweek/update/(realistic|optimistic)
  script: main.py
  login: required

- url: /teamform
  script: main.py
  login: required

- url: /team/(new|toggle|show|join|decline|leave)/([^/]*)
  script: main.py
  login: required

- url: /colleague/.*
  script: main.py
  login: required

- url: /.*
  script: error.py

inbound_services:
- mail
