application: snptzapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: receive_mail.py

- url: /scheduledtask
  script: send_mail.py
  login: admin

- url: /testdigest
  script: send_digest.py
  login: admin

- url: /
  script: main.py

- url: /settings
  script: main.py
  login: required

- url: /info
  script: main.py
  login: required

- url: /teams
  script: teams.py
  login: required

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robot.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /fixtures
  script: load_data.py
  login: required

- url: /.*
  script: error.py

inbound_services:
- mail
